services:
  app:
    command: yarn run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      app-init:
        condition: service_completed_successfully

  app-init:
    build:
      context: .
      target: development
    command: yarn
    volumes:
      - .:/app
