services:
  app:
    build:
      target: production
    expose:
      - 3000
    labels:
      - "traefik.http.routers.dockering.rule=Host(`$DEPLOY_URL`)"
      - "traefik.http.routers.dockering.entrypoints=web"


  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:2.9
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.web.address=:80


    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"

    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/letsencrypt:/letsencrypt
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
